package Recursion.RecursionOnStrings;

import java.util.ArrayList;

public class SubsequenceInArraylist {
    public static void main(String[] args) {
        /*
            A String is a subsequence of a given String that is
            generated by deleting some character of a given string
            without changing its order.

            Example :
            Total subsequence => 2^n
            Input : abc
            Output : a, b, c, ab, bc, ac, abc, null
         */
    }
}
